# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Rareș Nistor

[package]
name = "pixicons"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true
image.workspace = true
pixicons-macros = { path = "../pixicons-macros" }

[build-dependencies]
image = { workspace = true, features = ["rayon", "png"] }
