version = 1

# project meta
[[annotations]]
path = [
    ".gitignore",
    ".gitmodules",
    "Cargo.*",
    "rust-toolchain.toml",
    ".pre-commit-config.yaml",
]
SPDX-License-Identifier = ["MIT OR Apache-2.0 OR AGPL-3.0-or-later"]
SPDX-FileCopyrightText = "2026 Rareș Nistor"

# CI
[[annotations]]
path = [".github/workflows/**/*"]
SPDX-License-Identifier = ["MIT OR Apache-2.0 OR AGPL-3.0-or-later"]
SPDX-FileCopyrightText = "2026 Rareș Nistor"

#
# docs
#

# documentation
[[annotations]]
path = [
    "docs/**/*",
    "README.md",
    "CONTRIBUTING.md",
    "RELEASE-NOTES.md",
    "AGENTS.md",
    "CLAUDE.md",
    "logo.png",
]
precedence = "override"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "2026 Rareș Nistor"

# spec
[[annotations]]
path = ["docs/spec/**/*"]
precedence = "override"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Rareș Nistor"

#
# embedded assets
#

# RazzaSans (Nunito Sans) in PixFont Studio
[[annotations]]
path = ["crates/pixfont-studio/src/ui/font/RazzaSans/**/*"]
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2016 The Nunito Sans Project Authors (https://github.com/Fonthausen/NunitoSans)"

# Bootstrap Icons (until we replace them with our own)
[[annotations]]
path = ["external/bootstrap-icons/**/*"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Copyright (c) 2019-2024 The Bootstrap Authors"

# Bootstrap Icons (until we replace them with our own)
[[annotations]]
path = ["crates/ucd/src/ucd/**/*"]
SPDX-License-Identifier = "Unicode-3.0"
SPDX-FileCopyrightText = "© 2025 Unicode®, Inc."

#
# samples
#

[[annotations]]
path = ["samples/**/*"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Rareș Nistor"

#
# testing artifacts
#

# Pentacom fonts released as "Public Domain"
[[annotations]]
path = ["crates/pixfont/test/pentacom/born2b_sporty_v2.json"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "JapanYoshi"
