[toolchain]
channel = "stable"
profile = "default"
components = ["rustfmt", "clippy"]
targets = [
    # windows
    "i686-pc-windows-msvc",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",

    # mac
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",

    # linux
    "i686-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",

    # wasm
    "wasm32-unknown-unknown",
]
